// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)


// import { application } from "./application";

import ChatController from "./chat_controller"
application.register("chat", ChatController);


import ChatTriggerController from "./chat_trigger_controller"
application.register("chat-trigger", ChatTriggerController)


import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

// import AccordionController from "./controllers/accordion_controller"
// application.register("accordion", AccordionController)

// import { Application } from "@hotwired/stimulus"
// import ChatController from "./chat_controller"

// window.Stimulus = Application.start()
// Stimulus.register("chat", ChatController)