development:
  # adapter: async
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: ai_counsellor_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: ai_counsellor_production
